const CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Ahmedabad', 'Kolkata', 'Jaipur', 'Surat'];
const SKILLS = ['Concrete Work', 'Steel Framing', 'Electrical', 'Plumbing', 'Interior Design', 'Painting', 'Carpentry', 'Masonry', 'Roofing', 'Tiling', 'Welding', 'HVAC'];

const generateUsers = (role, count = 10) => {
  const names = {
    builder: ['Rajesh Kumar', 'Amit Sharma', 'Vikram Singh', 'Suresh Patel', 'Deepak Verma', 'Manoj Gupta', 'Anil Yadav', 'Sanjay Mishra', 'Ramesh Joshi', 'Prakash Rao'],
    contractor: ['Arun Mehta', 'Vishal Thakur', 'Rakesh Dubey', 'Sunil Pandey', 'Ajay Tiwari', 'Rohit Chauhan', 'Nitin Agarwal', 'Vivek Saxena', 'Karan Malhotra', 'Harsh Bansal'],
    client: ['Priya Nair', 'Sneha Reddy', 'Anita Desai', 'Ravi Iyer', 'Kavita Shah', 'Neha Kapoor', 'Pooja Menon', 'Sunita Bhatia', 'Arjun Das', 'Meera Pillai'],
    labourer: ['Raju Kewat', 'Mohan Pal', 'Shankar Das', 'Gopal Mandal', 'Bhola Prasad', 'Dinesh Sah', 'Lakshman Ram', 'Kallu Yadav', 'Sukhram Bind', 'Mangal Paswan'],
    skilled_labour: ['Farhan Sheikh', 'Imran Khan', 'Salim Ansari', 'Pappu Mistri', 'Ravi Electrician', 'Babu Plumber', 'Ashok Welder', 'Karim Painter', 'Jitendra Carpenter', 'Manoj Tiler'],
    dealer: ['Ganesh Traders', 'Shree Cement House', 'National Steel Corp', 'Gupta Building Materials', 'Patel Hardware', 'Singh Timber Mart', 'Bharat Electricals', 'Krishna Plumbing Supply', 'Om Sai Paints', 'Modern Tiles Gallery'],
  };
  const companies = {
    builder: ['Kumar Constructions', 'Sharma Builders', 'Singh Estates', 'Patel Infra', 'Verma Projects', 'Gupta Developers', 'Yadav Associates', 'Mishra Build Co', 'Joshi Construction', 'Rao Builders'],
    contractor: ['Mehta Contracts', 'Thakur Works', 'Dubey Services', 'Pandey Contractors', 'Tiwari Solutions', 'Chauhan Works', 'Agarwal Services', 'Saxena Contracts', 'Malhotra Group', 'Bansal Works'],
    dealer: ['Ganesh Traders LLP', 'Shree Cement Pvt Ltd', 'National Steel Corp', 'Gupta Materials Ltd', 'Patel Hardware Co', 'Singh Timber Pvt', 'Bharat Electricals', 'Krishna Plumbing Co', 'Om Sai Paints Ltd', 'Modern Tiles LLP'],
  };

  return Array.from({ length: count }, (_, i) => ({
    id: `${role}_${i + 1}`,
    name: names[role]?.[i] || `User ${i + 1}`,
    role,
    city: CITIES[i % CITIES.length],
    phone: `+91-${9000000000 + Math.floor(Math.random() * 999999999)}`,
    email: `${(names[role]?.[i] || 'user').toLowerCase().replace(/\s/g, '.')}@email.com`,
    company: companies[role]?.[i] || null,
    experience: role === 'client' ? null : Math.floor(Math.random() * 15) + 1,
    rating: (3.5 + Math.random() * 1.5).toFixed(1),
    reviewCount: Math.floor(Math.random() * 100) + 5,
    skills: SKILLS.sort(() => 0.5 - Math.random()).slice(0, 3),
    bio: `Experienced ${role} with years of expertise in the construction industry. Based in ${CITIES[i % CITIES.length]}.`,
    memberSince: `${2020 + (i % 5)}`,
    isVerified: Math.random() > 0.3,
    projectCount: Math.floor(Math.random() * 30) + 1,
    connections: Math.floor(Math.random() * 200) + 10,
    avatar: null,
  }));
};

export const MOCK_USERS = {
  builder: generateUsers('builder'),
  contractor: generateUsers('contractor'),
  client: generateUsers('client'),
  labourer: generateUsers('labourer'),
  skilled_labour: generateUsers('skilled_labour'),
  dealer: generateUsers('dealer'),
};

export const MOCK_CURRENT_USER = {
  id: 'current_user',
  name: 'Henil Patel',
  role: 'builder',
  city: 'Ahmedabad',
  phone: '+91-9876543210',
  email: 'henil.patel@stonebeam.in',
  company: 'StoneBeam-NH Constructions',
  experience: 8,
  rating: '4.8',
  reviewCount: 47,
  skills: ['Concrete Work', 'Steel Framing', 'Interior Design'],
  bio: 'Passionate builder with 8 years of experience in residential and commercial construction projects across Gujarat.',
  memberSince: '2022',
  isVerified: true,
  projectCount: 24,
  connections: 156,
  avatar: null,
};

export const MOCK_PROJECTS = [
  {
    id: 'proj_1',
    title: '3BHK Residential Villa',
    type: 'Residential',
    category: 'Construction',
    location: 'Ahmedabad',
    budget: { min: 2500000, max: 5000000 },
    startDate: '2025-07-01',
    endDate: '2026-03-31',
    description: 'Complete construction of a 3BHK villa with modern amenities, including landscaping and interior finishing.',
    skills: ['Concrete Work', 'Steel Framing', 'Interior Design'],
    priority: 'High',
    status: 'Open',
    postedBy: { name: 'Priya Nair', role: 'client', avatar: null },
    createdAt: '2 days ago',
    applicants: 12,
  },
  {
    id: 'proj_2',
    title: 'Commercial Office Renovation',
    type: 'Commercial',
    category: 'Renovation',
    location: 'Mumbai',
    budget: { min: 1500000, max: 3000000 },
    startDate: '2025-08-15',
    endDate: '2025-12-31',
    description: 'Renovate a 5000 sq ft commercial office space with new flooring, partitions, and electrical work.',
    skills: ['Electrical', 'Interior Design', 'Painting'],
    priority: 'Medium',
    status: 'In Progress',
    postedBy: { name: 'Ravi Iyer', role: 'client', avatar: null },
    createdAt: '5 days ago',
    applicants: 8,
  },
  {
    id: 'proj_3',
    title: 'Factory Warehouse Extension',
    type: 'Industrial',
    category: 'Construction',
    location: 'Pune',
    budget: { min: 8000000, max: 15000000 },
    startDate: '2025-09-01',
    endDate: '2026-06-30',
    description: 'Extend existing warehouse by 10,000 sq ft with steel structure and concrete flooring.',
    skills: ['Steel Framing', 'Concrete Work', 'Roofing'],
    priority: 'High',
    status: 'Open',
    postedBy: { name: 'Rajesh Kumar', role: 'builder', avatar: null },
    createdAt: '1 day ago',
    applicants: 5,
  },
  {
    id: 'proj_4',
    title: 'Kitchen & Bathroom Remodel',
    type: 'Renovation',
    category: 'Interior',
    location: 'Bangalore',
    budget: { min: 500000, max: 1200000 },
    startDate: '2025-07-15',
    endDate: '2025-09-30',
    description: 'Complete remodel of kitchen and 2 bathrooms in a luxury apartment.',
    skills: ['Plumbing', 'Tiling', 'Carpentry'],
    priority: 'Medium',
    status: 'Open',
    postedBy: { name: 'Sneha Reddy', role: 'client', avatar: null },
    createdAt: '3 days ago',
    applicants: 15,
  },
  {
    id: 'proj_5',
    title: 'Electrical Wiring — New Building',
    type: 'Residential',
    category: 'Electrical',
    location: 'Delhi',
    budget: { min: 300000, max: 800000 },
    startDate: '2025-07-10',
    endDate: '2025-10-10',
    description: 'Complete electrical wiring and panel installation for a new 4-storey residential building.',
    skills: ['Electrical', 'HVAC'],
    priority: 'High',
    status: 'In Progress',
    postedBy: { name: 'Amit Sharma', role: 'builder', avatar: null },
    createdAt: '1 week ago',
    applicants: 7,
  },
  {
    id: 'proj_6',
    title: 'Swimming Pool Construction',
    type: 'Residential',
    category: 'Construction',
    location: 'Hyderabad',
    budget: { min: 1000000, max: 2500000 },
    startDate: '2025-08-01',
    endDate: '2025-11-30',
    description: 'Build an outdoor swimming pool with deck area and changing rooms.',
    skills: ['Concrete Work', 'Plumbing', 'Tiling'],
    priority: 'Low',
    status: 'Open',
    postedBy: { name: 'Kavita Shah', role: 'client', avatar: null },
    createdAt: '4 days ago',
    applicants: 3,
  },
  {
    id: 'proj_7',
    title: 'Road Resurfacing Project',
    type: 'Commercial',
    category: 'Civil',
    location: 'Jaipur',
    budget: { min: 5000000, max: 10000000 },
    startDate: '2025-10-01',
    endDate: '2026-02-28',
    description: 'Resurface 2km of main road with asphalt including drainage improvements.',
    skills: ['Concrete Work', 'Masonry'],
    priority: 'High',
    status: 'Closed',
    postedBy: { name: 'Vikram Singh', role: 'builder', avatar: null },
    createdAt: '2 weeks ago',
    applicants: 20,
  },
  {
    id: 'proj_8',
    title: 'Luxury Penthouse Interior',
    type: 'Residential',
    category: 'Interior',
    location: 'Chennai',
    budget: { min: 3000000, max: 7000000 },
    startDate: '2025-08-15',
    endDate: '2026-01-15',
    description: 'Full interior design and execution for a luxury penthouse including custom furniture.',
    skills: ['Interior Design', 'Carpentry', 'Painting'],
    priority: 'Medium',
    status: 'In Progress',
    postedBy: { name: 'Meera Pillai', role: 'client', avatar: null },
    createdAt: '6 days ago',
    applicants: 10,
  },
];

export const MOCK_ORDERS = [
  {
    id: 'ORD-20250601',
    itemName: 'UltraTech Cement (OPC 53)',
    category: 'Cement',
    categoryIcon: 'cube',
    quantity: 200,
    unit: 'bags',
    unitPrice: 380,
    total: 76000,
    supplier: { name: 'Shree Cement House', avatar: null },
    buyer: { name: 'Rajesh Kumar', avatar: null },
    status: 'Delivered',
    orderedDate: '2025-06-01',
    deliveredDate: '2025-06-04',
    progress: 4,
  },
  {
    id: 'ORD-20250605',
    itemName: 'TMT Steel Bars (Fe-500)',
    category: 'Steel',
    categoryIcon: 'pipe',
    quantity: 5,
    unit: 'tons',
    unitPrice: 52000,
    total: 260000,
    supplier: { name: 'National Steel Corp', avatar: null },
    buyer: { name: 'Amit Sharma', avatar: null },
    status: 'In Progress',
    orderedDate: '2025-06-05',
    deliveredDate: null,
    progress: 3,
  },
  {
    id: 'ORD-20250607',
    itemName: 'Birla White Cement',
    category: 'Cement',
    categoryIcon: 'cube',
    quantity: 50,
    unit: 'bags',
    unitPrice: 550,
    total: 27500,
    supplier: { name: 'Gupta Building Materials', avatar: null },
    buyer: { name: 'Vikram Singh', avatar: null },
    status: 'Pending',
    orderedDate: '2025-06-07',
    deliveredDate: null,
    progress: 1,
  },
  {
    id: 'ORD-20250603',
    itemName: 'Havells Copper Wire (4mm)',
    category: 'Electrical',
    categoryIcon: 'flash',
    quantity: 10,
    unit: 'coils',
    unitPrice: 4500,
    total: 45000,
    supplier: { name: 'Bharat Electricals', avatar: null },
    buyer: { name: 'Suresh Patel', avatar: null },
    status: 'Cancelled',
    orderedDate: '2025-06-03',
    deliveredDate: null,
    progress: 0,
  },
  {
    id: 'ORD-20250608',
    itemName: 'Asian Paints Royale (20L)',
    category: 'Paints',
    categoryIcon: 'format-paint',
    quantity: 15,
    unit: 'buckets',
    unitPrice: 3200,
    total: 48000,
    supplier: { name: 'Om Sai Paints', avatar: null },
    buyer: { name: 'Deepak Verma', avatar: null },
    status: 'In Progress',
    orderedDate: '2025-06-08',
    deliveredDate: null,
    progress: 2,
  },
];

export const MOCK_ATTENDANCE = [
  { id: 'att_1', date: '2025-06-01', site: 'Ahmedabad Villa Project', shift: '8:00 AM - 5:00 PM', hoursWorked: 8, contractor: 'Arun Mehta', status: 'Present', checkIn: '7:55 AM', checkOut: '5:10 PM' },
  { id: 'att_2', date: '2025-06-02', site: 'Ahmedabad Villa Project', shift: '8:00 AM - 5:00 PM', hoursWorked: 8, contractor: 'Arun Mehta', status: 'Present', checkIn: '8:02 AM', checkOut: '5:00 PM' },
  { id: 'att_3', date: '2025-06-03', site: 'Mumbai Office Renovation', shift: '9:00 AM - 6:00 PM', hoursWorked: 4, contractor: 'Vishal Thakur', status: 'Half Day', checkIn: '9:10 AM', checkOut: '1:15 PM' },
  { id: 'att_4', date: '2025-06-04', site: 'Mumbai Office Renovation', shift: '9:00 AM - 6:00 PM', hoursWorked: 0, contractor: 'Vishal Thakur', status: 'Absent', checkIn: null, checkOut: null },
  { id: 'att_5', date: '2025-06-05', site: 'Ahmedabad Villa Project', shift: '8:00 AM - 5:00 PM', hoursWorked: 8, contractor: 'Arun Mehta', status: 'Present', checkIn: '7:50 AM', checkOut: '5:05 PM' },
];

export const MOCK_DEALER_CATALOGUE = [
  { id: 'cat_1', name: 'UltraTech Cement OPC 53', category: 'Cement', price: 380, unit: 'per bag (50kg)', inStock: true, rating: '4.5', icon: 'cube' },
  { id: 'cat_2', name: 'TMT Steel Bars Fe-500', category: 'Steel', price: 52000, unit: 'per ton', inStock: true, rating: '4.7', icon: 'pipe' },
  { id: 'cat_3', name: 'M-Sand (Manufactured Sand)', category: 'Sand', price: 1800, unit: 'per cu.m', inStock: true, rating: '4.2', icon: 'grain' },
  { id: 'cat_4', name: 'Red Clay Bricks (Class A)', category: 'Bricks', price: 8, unit: 'per piece', inStock: false, rating: '4.0', icon: 'wall' },
  { id: 'cat_5', name: 'Havells Wire 4mm Copper', category: 'Electrical', price: 4500, unit: 'per coil', inStock: true, rating: '4.6', icon: 'flash' },
  { id: 'cat_6', name: 'Asian Paints Royale 20L', category: 'Paints', price: 3200, unit: 'per bucket', inStock: true, rating: '4.8', icon: 'format-paint' },
];

export const MOCK_BANNERS = [
  { id: 'b1', title: 'Find Top Contractors Near You', subtitle: 'Connect with 500+ verified contractors', gradient: ['#7b2cbf', '#9d4edd'] },
  { id: 'b2', title: 'Post Your Project Today', subtitle: 'Get bids from trusted builders', gradient: ['#5a189a', '#7b2cbf'] },
  { id: 'b3', title: 'Best Deals on Materials', subtitle: 'Save up to 20% on bulk orders', gradient: ['#2ecc71', '#27ae60'] },
];

export const MOCK_FEED = [
  { id: 'f1', title: '3BHK Villa project updated', project: 'Ahmedabad Villa', status: 'In Progress', timeAgo: '2 hours ago', type: 'update' },
  { id: 'f2', title: 'New bid received', project: 'Office Renovation', status: 'Open', timeAgo: '5 hours ago', type: 'bid' },
  { id: 'f3', title: 'Order dispatched', project: 'TMT Steel — ORD-20250605', status: 'In Progress', timeAgo: '1 day ago', type: 'order' },
  { id: 'f4', title: 'Contractor joined your project', project: 'Factory Extension', status: 'In Progress', timeAgo: '2 days ago', type: 'join' },
  { id: 'f5', title: 'Payment received', project: 'Kitchen Remodel', status: 'Completed', timeAgo: '3 days ago', type: 'payment' },
];

export const formatCurrency = (amount) => {
  if (amount >= 10000000) return `₹${(amount / 10000000).toFixed(1)}Cr`;
  if (amount >= 100000) return `₹${(amount / 100000).toFixed(1)}L`;
  if (amount >= 1000) return `₹${(amount / 1000).toFixed(1)}K`;
  return `₹${amount}`;
};
