export const ROLES = {
  BUILDER: 'builder',
  CONTRACTOR: 'contractor',
  CLIENT: 'client',
  LABOURER: 'labourer',
  SKILLED_LABOUR: 'skilled_labour',
  DEALER: 'dealer',
};

export const ROLE_CONFIG = {
  [ROLES.BUILDER]: {
    id: ROLES.BUILDER,
    label: 'Builder',
    icon: 'office-building',
    emoji: '🏗️',
    descriptor: 'Manage & build projects',
    quickActions: [
      { id: 'create_project', label: 'Create Project', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { id: 'find_contractor', label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { id: 'find_dealer', label: 'Find Dealer', icon: 'store', screen: 'FindDealer' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create Projects', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { label: 'Find Dealer', icon: 'store', screen: 'FindDealer' },
      { label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create', icon: 'plus', screen: 'CreateProject', isFab: true },
      { label: 'Dealers', icon: 'store', screen: 'FindDealer' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
  [ROLES.CONTRACTOR]: {
    id: ROLES.CONTRACTOR,
    label: 'Contractor',
    icon: 'account-hard-hat',
    emoji: '👷',
    descriptor: 'Contract & execute work',
    quickActions: [
      { id: 'find_projects', label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { id: 'find_builder', label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { id: 'find_clients', label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create Projects', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { label: 'Find Dealer', icon: 'store', screen: 'FindDealer' },
      { label: 'Find Electrician/Plumber', icon: 'flash', screen: 'FindElectricianPlumber' },
      { label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Projects', icon: 'magnify', screen: 'FindProject', isFab: true },
      { label: 'Builder', icon: 'office-building', screen: 'FindBuilder' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
  [ROLES.CLIENT]: {
    id: ROLES.CLIENT,
    label: 'Client',
    icon: 'handshake',
    emoji: '🤝',
    descriptor: 'Commission projects',
    quickActions: [
      { id: 'create_project', label: 'Create Project', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { id: 'find_builder', label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { id: 'find_contractor', label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create Projects', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { label: 'Find Dealer', icon: 'store', screen: 'FindDealer' },
      { label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { label: 'Find Electrician/Plumber', icon: 'flash', screen: 'FindElectricianPlumber' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create', icon: 'plus', screen: 'CreateProject', isFab: true },
      { label: 'Builder', icon: 'office-building', screen: 'FindBuilder' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
  [ROLES.LABOURER]: {
    id: ROLES.LABOURER,
    label: 'Labourer',
    icon: 'hammer',
    emoji: '🔨',
    descriptor: 'Daily work & attendance',
    quickActions: [
      { id: 'attendance', label: 'Attendance', icon: 'calendar-check', screen: 'Attendance' },
      { id: 'work_status', label: 'Work Status', icon: 'wrench', screen: 'WorkStatus' },
      { id: 'find_contractor', label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Attendance', icon: 'calendar-check', screen: 'Attendance' },
      { label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { label: 'Work Status', icon: 'wrench', screen: 'WorkStatus' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Attendance', icon: 'calendar-check', screen: 'Attendance', isFab: true },
      { label: 'Work', icon: 'wrench', screen: 'WorkStatus' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
  [ROLES.SKILLED_LABOUR]: {
    id: ROLES.SKILLED_LABOUR,
    label: 'Skilled Labour',
    icon: 'flash',
    emoji: '⚡',
    descriptor: 'Specialized trade work',
    quickActions: [
      { id: 'find_projects', label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { id: 'find_clients', label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { id: 'find_contractor', label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Projects', icon: 'magnify', screen: 'FindProject', isFab: true },
      { label: 'Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
  [ROLES.DEALER]: {
    id: ROLES.DEALER,
    label: 'Dealer',
    icon: 'store',
    emoji: '🏪',
    descriptor: 'Supply materials & products',
    quickActions: [
      { id: 'create_project', label: 'Create Project', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { id: 'find_builder', label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { id: 'find_clients', label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { id: 'order_status', label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
    ],
    drawerMenu: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create Project', icon: 'clipboard-plus-outline', screen: 'CreateProject' },
      { label: 'Find Projects', icon: 'magnify', screen: 'FindProject' },
      { label: 'Find Builder', icon: 'office-building', screen: 'FindBuilder' },
      { label: 'Find Contractor', icon: 'account-hard-hat', screen: 'FindContractor' },
      { label: 'Find Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Order Status', icon: 'package-variant', screen: 'OrderStatus' },
      { label: 'Settings', icon: 'cog', screen: 'Settings' },
      { label: 'About Us', icon: 'information', screen: 'AboutUs' },
      { label: 'Customer Care', icon: 'phone', screen: 'CustomerCare' },
    ],
    bottomTabs: [
      { label: 'Home', icon: 'home', screen: 'Home' },
      { label: 'Profile', icon: 'account', screen: 'Profile' },
      { label: 'Create', icon: 'plus', screen: 'CreateProject', isFab: true },
      { label: 'Clients', icon: 'handshake', screen: 'FindClient' },
      { label: 'Orders', icon: 'package-variant', screen: 'OrderStatus' },
    ],
  },
};

export const ROLE_LIST = Object.values(ROLE_CONFIG);

export default ROLE_CONFIG;
